platform :ios
inhibit_all_warnings!
pod 'JSONKit'
pod 'Lockbox'
pod 'MWFeedParser'
pod 'NSData+Base64'
pod 'OBSlider'
pod 'GMGridView'
pod 'ISO8601DateFormatter'
pod 'FlurrySDK'
pod 'SDURLCache'
pod 'BlockAlertsAnd-ActionSheets'
pod 'GCDiscreetNotificationView'
pod 'MBProgressHUD'
pod 'Appirater'
pod 'NSLogger'
pod 'NSLogger-CocoaLumberjack-connector', :git => 'git://github.com/steipete/NSLogger-CocoaLumberjack-connector.git', :commit=> '444fa49e9f'
