platform :ios
inhibit_all_warnings!
pod 'JSONKit'
pod 'Lockbox'
pod 'SSToolkit'
pod 'MWFeedParser'
pod 'NSData+Base64'
pod 'OBSlider'
pod 'GMGridView'
pod 'FlurrySDK'
pod 'SDURLCache'
pod 'BlockAlertsAnd-ActionSheets'
pod 'GCDiscreetNotificationView'
pod 'MBProgressHUD'
pod 'MagicalRecord', :git=>'https://github.com/blackgold9/MagicalRecord.git', :branch=>'ios5Fixes', :commit => 'c545183'
pod 'iRate'
pod 'NSLogger'
pod 'NSLogger-CocoaLumberjack-connector'
