platform :ios
inhibit_all_warnings!
pod 'JSONKit'
pod 'Lockbox'
pod 'SSToolkit'
pod 'MWFeedParser'
pod 'NSData+Base64'
pod 'OBSlider'
pod 'FlurrySDK'
pod 'SDURLCache'
pod 'BlockAlertsAnd-ActionSheets'
pod 'GCDiscreetNotificationView'
pod 'MBProgressHUD'
pod 'iRate'
pod 'MagicalRecord'
pod 'NSLogger'
pod 'NSLogger-CocoaLumberjack-connector'
